version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.10
        commands:
             - pip install --upgrade pip
             - pip install pylint
               # Install dependencies needed for running the static analysis
             - pip install -r requirements.txt 
pre_build:
    commands:
     - python --version
     - pylint $CODEBUILD_SRC_DIR/*.py || true
     - pylint $CODEBUILD_SRC_DIR/trav/*.py || true
     - pylint $CODEBUILD_SRC_DIR/travelling/*.py || true
         
artifacts:
    files:
     - '**/*'